### ISSUE TITLE
Bug Report: Incorrect port number on server for Postgres instance

### ISSUE THREAD

**Issue by kiptoomm** [amplication/plugins#36]
The generated file on the resulting project from [Getting Started docs](https://docs.amplication.com/getting-started/view-generated-code/) `server/docker-compose.yml` contains this line:

`DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5433`

I ran this query against the server:

And got a `500` response. This was the server console stack trace:

```
[Nest] 1  - 12/19/2022, 2:15:19 PM   ERROR [ExceptionsHandler]
Invalid `this.prisma.user.findUnique()` invocation in
/app/dist/user/base/user.service.base.js:17:33
  14     return this.prisma.user.findMany(args);
  15 }
  16 async findOne(args) {
→ 17     return this.prisma.user.findUnique(args)
  Can't reach database server at `db`:`5433`
Please make sure your database server is running at `db`:`5433`.
Error:
Invalid `this.prisma.user.findUnique()` invocation in
/app/dist/user/base/user.service.base.js:17:33
  14     return this.prisma.user.findMany(args);
  15 }
  16 async findOne(args) {
→ 17     return this.prisma.user.findUnique(args)
  Can't reach database server at `db`:`5433`
Please make sure your database server is running at `db`:`5433`.
    at RequestHandler.request (/app/node_modules/@prisma/client/runtime/index.js:49028:15)
    at async PrismaService._request (/app/node_modules/@prisma/client/runtime/index.js:49919:18)
    at async AuthService.validateUser (/app/dist/auth/auth.service.js:24:22)
    at async AuthService.login (/app/dist/auth/auth.service.js:36:22)
```

Shouldn't the generated db port value be 5432, just like for the `db` and `migrate` services?

**Comment by abrl91** [comment]
@kiptoomm did you run `npm run docker:db`?

**Comment by abrl91** [comment]
The DSG version is not using the updated version of this fix. I will create a PR to fix it
